#!/usr/bin/env python3
""" Skeleton Implementation of Project 2 for NEU CS3700 """

import argparse
import json
import select
import socket

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"
NEXT = "next"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"


##########################################################################################

class Router:
  """ Your Router """
  def __init__(self, asn, networks):
    self.routes = []
    self.updates = []
    self.revocations = []
    self.relations = {}
    self.sockets = {}
    self.asn = asn[0]
    self.ip = Utils()
    for relationship in networks:
      network, relation = relationship.split("-")
      self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
      self.sockets[network].setblocking(0)
      self.sockets[network].connect(network)
      self.relations[network] = relation

  def lookup_routes(self, daddr):
    """ Lookup all valid routes for an address """
    outroutes = self.routes.copy()
    addr = daddr.split(".")
    # loop through each route in the table, dropping any that don't lead to daddr
    for i in range(0, len(self.routes)):
      netmask = self.routes[i].copy()[NMSK].split(".")
      split_dest = self.routes[i].copy()[DEST].split(".")
      # loop through each number in the IP, drop the IP if it leads somewhere other than daddr
      for j in range(0, 4):
        if netmask[j] == "255" and addr[j] != split_dest[j]:
          outroutes.remove(self.get_dict(outroutes, self.routes[i].copy()[DEST], DEST))
          break
    return outroutes

  def get_shortest_as_path(self, routes):
    """ select the route with the shortest AS Path """
    # find the minimum AS path length from all routes
    min_as_path = min(map((lambda x: len(x[APTH])), routes))
    # filter out any routes with AS paths that aren't as short as the minimum
    return list(filter((lambda x: len(x[APTH]) == min_as_path), routes.copy()))

  def get_highest_preference(self, routes):
    """ select the route(s) with the highest preference """
    # pull out all the localpref values from the routing table and find the max
    max_pref = max(map((lambda x: x[LPRF]), routes))
    # filter out all routes that don't have a localpref as good as the max
    return list(filter((lambda x: x[LPRF] == max_pref), routes.copy()))

  def get_self_origin(self, routes):
    """ select self originating routes """
    # determine if any of the routes are self-originating
    self_origin = True in map((lambda x: x[SORG]), routes)
    if self_origin:
      # if there is at least one self-originating route, return all the self-originating routes
      outroutes = list(filter((lambda x: x[SORG]), routes.copy()))
    else:
      # if there are no self-originating routes, return all the routes
      outroutes = routes.copy()
    return outroutes

  def get_origin_routes(self, routes):
    """ select origin routes: IGP > EGP > UNK """
    # get all the origin routes
    origin_routes = map((lambda x: x[ORIG]), routes)
    if "IGP" in origin_routes:
      # if EGP routes exist, filter out all the others
      return list(filter((lambda x: x[ORIG] == "IGP"), routes.copy()))
    elif "EGP" in origin_routes:
      # if no IGP routes exist but EGP routes exist, filter out all the non-EGP routes
      return list(filter((lambda x: x[ORIG] == "EGP"), routes.copy()))
    else:
      # if no IGP or EGP routes exit, don't filter anything out
      return routes.copy()

  def filter_relationships(self, srcif, routes):
    """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
    # outroutes = []
    # return outroutes
    return routes

  def get_route(self, srcif, daddr):
    """ Select the best route for a given address """
    # TODO
    peer = None
    routes = self.lookup_routes(daddr)
    # Rules go here
    if routes:
      # 1. Highest Preference
      routes = self.get_highest_preference(routes)
      # 2. Self Origin
      routes = self.get_self_origin(routes)
      # 3. Shortest ASPath
      routes = self.get_shortest_as_path(routes)
      # 4. EGP > IGP > UNK
      routes = self.get_origin_routes(routes)
      # 5. Lowest IP Address
      last = "255.255.255.255"
      for i in range(0, len(routes)):
        peer = self.ip.least(last, routes[i][NEXT])
        last = routes[i][NEXT]
      # Final check: enforce peering relationships
      routes = self.filter_relationships(srcif, routes)
    return self.sockets[self.get_dict(routes, peer, NEXT)[NEXT]] if peer else None

  def forward(self, srcif, packet):
    """ Forward a data packet """
    # self.get_route(srcif, packet[DEST]).sendall(json.dumps(packet).encode())
    # TODO put this back in the try-except
    try:
      self.get_route(srcif, packet[DEST]).sendall(json.dumps(packet).encode())
    except:
      return False
    return True

  def coalesce(self):
    """ coalesce any routes that are right next to each other """
    # TODO (this is the most difficult task, save until last)
    return False

  def update(self, srcif, packet):
    """ handle update packets """
    # add entry to routing table
    # TODO change this so that it is only added if it is better than what was there before
    self.routes.append({DEST: packet[MESG][NTWK], NEXT: srcif, NMSK: packet[MESG][NMSK], LPRF: int(packet[MESG][LPRF]), \
      SORG: packet[MESG][SORG], APTH: packet[MESG][APTH], ORIG: packet[MESG][ORIG]})
    # store the packet in case we need it later
    self.updates.append(packet.copy())
    # create a modified copy of the packet to update neighbors
    update_packet = packet.copy()
    # update_packet[SRCE] = packet[DEST] WRONG
    update_packet[MESG][APTH].append(int(self.asn))
    # update all the neighbors
    for neighbor in self.sockets.keys():
      if neighbor != srcif:
        update_packet[SRCE] = self.ip.get_local_version(neighbor)
        update_packet[DEST] = neighbor
        self.sockets[neighbor].sendall(json.dumps(update_packet).encode())
    # TODO change this so that only the necessary neighbors are updated
    return True

  def revoke(self, packet):
    """ handle revoke packets """
    self.revocations.append(packet.copy())
    for revocation in packet[MESG]:
      self.remove_from_routing_table(revocation[NTWK], revocation[NMSK])

    revoke_packet = packet.copy()
    for neighbor in self.sockets.keys():
      if neighbor != packet[SRCE]:
        revoke_packet[SRCE] = self.ip.get_local_version(neighbor)
        revoke_packet[DEST] = neighbor
        self.sockets[neighbor].sendall(json.dumps(revoke_packet).encode())
    return True

  def remove_from_routing_table(self, net, mask):
    self.routes = list(filter((lambda x: x[DEST] == net or x[NMSK] == mask), self.routes))

  def dump(self, packet):
    """ handles dump table requests """
    # copy the packet and modify its fields to make it a table packet
    table_packet = packet.copy()
    table_packet[SRCE] = packet[DEST]
    table_packet[DEST] = packet[SRCE]
    table_packet[TYPE] = "table"
    table_packet[MESG] = json.loads("[]")
    # for each route, add an entry to the msg field of the table packet
    for route in self.routes:
      table_packet[MESG].append(json.loads("{\"network\" : \"" + route[DEST] + "\", \"netmask\" : \"" + \
        route[NMSK] + "\", \"peer\" : \"" + route[NEXT] + "\"}"))
    self.sockets[packet[SRCE]].sendall(json.dumps(table_packet).encode())
    return True

  def handle_packet(self, srcif, packet):
    """ dispatches a packet """
    if packet[TYPE] == UPDT:
      return self.update(srcif, packet)
    elif packet[TYPE] == RVKE:
      return self.revoke(packet)
    elif packet[TYPE] == DATA:
      return self.forward(srcif, packet)
    elif packet[TYPE] == NRTE:
      return False
    elif packet[TYPE] == DUMP:
      return self.dump(packet)
    return False

  def send_error(self, conn, msg):
    """ Send a no_route error message """
    print("ERROR!!!\n\n")
    print(msg)

  def run(self):
    """ main loop for the router """
    while True:
      socks = select.select(self.sockets.values(), [], [], 0.1)[0]
      for conn in socks:
        try:
          k = conn.recv(65535)
        except:
          # either died on a connection reset, or was SIGTERM's by parent
          return
        if k:
          for sock in self.sockets:
            if self.sockets[sock] == conn:
              srcif = sock
          msg = json.loads(k)
          if not self.handle_packet(srcif, msg):
            self.send_error(conn, msg)
        else:
          return

  def get_dict(self, routes, ip, key):
    """ Return the first element in the routes provided which has a key that matches ip.
    """
    for route in routes:
      if route[key] == ip:
        return route
    return None

  def get_keys(self):
    """ Get the DEST keys associated with the routing table.
    """
    return list(map((lambda x: x[DEST]), self.routes.copy()))

class Utils:
  def get_local_version(self, neighbor):
    """ get local IP associated with provided neighbor IP """
    local = list(neighbor)
    local[len(local) - 1] = "1"
    return "".join(local)

  def subnet_to_cidr(self, subnet):
    """ convert subnet mask to cidr """
    nums = subnet.split(".")
    bins = [bin(nums[0]), bin(nums[1]), bin(nums[2]), bin(nums[3])]
    cidr = 0
    for num in bins:
      binary = list(num)
      for i in range(2, len(binary)):
        if binary[i] == "1":
          cidr = cidr + 1
    # TODO delete this method if it's not useful
    return cidr

  def least(self, this, that):
    """ return the lower of two IP addresses """
    split_this = this.split(".")
    split_that = that.split(".")
    for i in range(0, 4):
      for j in range(0, 4):
        if int(split_this[i]) > int(split_that[j]):
          return that
        else:
          return this
    return this

if __name__ == "__main__":
  PARSER = argparse.ArgumentParser(description='route packets')
  PARSER.add_argument('asn', metavar='asn', type=int, nargs=1, help='asn')
  PARSER.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
  ARGS = PARSER.parse_args()
  Router(ARGS.asn, ARGS.networks).run()
